name: dart_quic
description: A Dart QUIC library built on quinn via FFI, with async client/server API and stream/datagram support.
version: 0.1.0
homepage: https://github.com/arcticfox1919/dart-quic
repository: https://github.com/arcticfox1919/dart-quic


topics:
  - quic
  - quinn
  - QUIC

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  ffi: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  ffigen: ^20.1.1
